### ISSUE TITLE
xf86-video-armsoc on odroid c1

### ISSUE THREAD

**Issue by xlazom00** [endlessm/xf86-video-armsoc#29]
Hi
I would like to use this on odroid c1, but it looks like I will need proper mali r5p1 with dma-buf
Can anybody share proper userspace binary drivers?

**Comment by magcius** [comment]
I don't think there's anything we can say other than to contact ODROID for an updated set of binary Mali drivers. We at Endless have them internally, but I'm not sure if we're allowed to redistribute binary versions of our drivers. I'll check with our team on Monday. @dsd @blandford ?

You could also use an old revision of before we migrated away from UMP and towards DMA-BUF in the meantime.

**Comment by xlazom00** [comment]
so?

**Comment by dsd** [comment]
Sorry, no capacity to support this at this time.
However, the standard upstream xf86-video-armsoc may work well enough for your needs, I suggest trying that first. In order to do that you would need to take the `meson` drm display controller driver from endlessm/linux-meson.
